// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6I_xJ0cN_q5Kz-ujmFMmPQ2THkanT3aQ',
    appId: '1:228834943626:web:ddf9451a689cc9f2270373',
    messagingSenderId: '228834943626',
    projectId: 'firstloveyourself-b0c13',
    authDomain: 'firstloveyourself-b0c13.firebaseapp.com',
    storageBucket: 'firstloveyourself-b0c13.firebasestorage.app',
    measurementId: 'G-YB5RTE876E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABrmJQsh_KnWO8cm2xiwtUJKd8-k8VGVw',
    appId: '1:228834943626:android:aabe4a5c0c23d63d270373',
    messagingSenderId: '228834943626',
    projectId: 'firstloveyourself-b0c13',
    storageBucket: 'firstloveyourself-b0c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe3ph1x4Ki55X0kMUlFUd17jxrJbIvh8o',
    appId: '1:228834943626:ios:8b30d8dcf8d2f77e270373',
    messagingSenderId: '228834943626',
    projectId: 'firstloveyourself-b0c13',
    storageBucket: 'firstloveyourself-b0c13.firebasestorage.app',
    iosBundleId: 'com.example.fly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe3ph1x4Ki55X0kMUlFUd17jxrJbIvh8o',
    appId: '1:228834943626:ios:d7d154f2ef449868270373',
    messagingSenderId: '228834943626',
    projectId: 'firstloveyourself-b0c13',
    storageBucket: 'firstloveyourself-b0c13.firebasestorage.app',
    iosBundleId: 'com.example.flyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6I_xJ0cN_q5Kz-ujmFMmPQ2THkanT3aQ',
    appId: '1:228834943626:web:1b4e5970d6252bb7270373',
    messagingSenderId: '228834943626',
    projectId: 'firstloveyourself-b0c13',
    authDomain: 'firstloveyourself-b0c13.firebaseapp.com',
    storageBucket: 'firstloveyourself-b0c13.firebasestorage.app',
    measurementId: 'G-K362398H5R',
  );
}
